---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ub-proxy
  namespace: zhujq
spec:
  selector:
    matchLabels:
      app: ub-proxy
  replicas: 1
  template:
    metadata:
      labels:
        app: ub-proxy
    spec:
      containers:
        - name: ub-proxy
          image: zhujq/web-proxy
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /data
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
            
