apiVersion: apps/v1
kind: Deployment
metadata:
  name: ub-proxy
  namespace: zhujq
spec:
  selector:
    matchLabels:
      app: ub-proxy
  replicas: 1
  template:
    metadata:
      labels:
        app: ub-proxy
    spec:
      containers:
        - name: ub-proxy
          image: zhujq/web-proxy
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080

